//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRule) DeepCopyInto(out *DNSRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRule.
func (in *DNSRule) DeepCopy() *DNSRule {
	if in == nil {
		return nil
	}
	out := new(DNSRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ICMPRule) DeepCopyInto(out *ICMPRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ICMPRule.
func (in *ICMPRule) DeepCopy() *ICMPRule {
	if in == nil {
		return nil
	}
	out := new(ICMPRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPRangeRule) DeepCopyInto(out *IPRangeRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPRangeRule.
func (in *IPRangeRule) DeepCopy() *IPRangeRule {
	if in == nil {
		return nil
	}
	out := new(IPRangeRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MTURule) DeepCopyInto(out *MTURule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MTURule.
func (in *MTURule) DeepCopy() *MTURule {
	if in == nil {
		return nil
	}
	out := new(MTURule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkValidator) DeepCopyInto(out *NetworkValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkValidator.
func (in *NetworkValidator) DeepCopy() *NetworkValidator {
	if in == nil {
		return nil
	}
	out := new(NetworkValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkValidatorList) DeepCopyInto(out *NetworkValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkValidatorList.
func (in *NetworkValidatorList) DeepCopy() *NetworkValidatorList {
	if in == nil {
		return nil
	}
	out := new(NetworkValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkValidatorSpec) DeepCopyInto(out *NetworkValidatorSpec) {
	*out = *in
	if in.DNSRules != nil {
		in, out := &in.DNSRules, &out.DNSRules
		*out = make([]DNSRule, len(*in))
		copy(*out, *in)
	}
	if in.ICMPRules != nil {
		in, out := &in.ICMPRules, &out.ICMPRules
		*out = make([]ICMPRule, len(*in))
		copy(*out, *in)
	}
	if in.IPRangeRules != nil {
		in, out := &in.IPRangeRules, &out.IPRangeRules
		*out = make([]IPRangeRule, len(*in))
		copy(*out, *in)
	}
	if in.MTURules != nil {
		in, out := &in.MTURules, &out.MTURules
		*out = make([]MTURule, len(*in))
		copy(*out, *in)
	}
	if in.TCPConnRules != nil {
		in, out := &in.TCPConnRules, &out.TCPConnRules
		*out = make([]TCPConnRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkValidatorSpec.
func (in *NetworkValidatorSpec) DeepCopy() *NetworkValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkValidatorStatus) DeepCopyInto(out *NetworkValidatorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkValidatorStatus.
func (in *NetworkValidatorStatus) DeepCopy() *NetworkValidatorStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkValidatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPConnRule) DeepCopyInto(out *TCPConnRule) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPConnRule.
func (in *TCPConnRule) DeepCopy() *TCPConnRule {
	if in == nil {
		return nil
	}
	out := new(TCPConnRule)
	in.DeepCopyInto(out)
	return out
}
